import * as z from 'zod';

export const actaMaximaAutoridadSchema = z.object({
  // --- Datos Generales ---
  email: z
    .string()
    .min(1, 'Campo Requerido')
    .email({ message: 'Debe ser un correo válido.' }),
  rifOrgano: z.string().min(1, 'El RIF es requerido.'),
  denominacionCargoEntrega: z
    .string()
    .min(1, 'La denominación del cargo es requerida.'),
  nombreOrgano: z.string().min(1, 'El nombre del órgano es requerido.'),
  ciudadSuscripcion: z.string().min(1, 'La ciudad es requerida.'),
  estadoSuscripcion: z.string().min(1, 'El estado es requerido.'),
  horaSuscripcion: z.string().min(1, 'La hora es requerida.'),
  fechaSuscripcion: z.string().min(1, 'La fecha es requerida.'),
  direccionOrgano: z.string().min(1, 'La dirección es requerida.'),
  motivoEntrega: z.string().min(1, 'Debe seleccionar un motivo.'),

  // --- Servidores Públicos y Testigos ---
  nombreServidorEntrante: z.string().min(1, 'Este campo es requerido.'),
  cedulaServidorEntrante: z.string().min(1, 'Este campo es requerido.'),
  profesionServidorEntrante: z.string().min(1, 'Este campo es requerido.'),
  designacionServidorEntrante: z.string().min(1, 'Este campo es requerido.'),
  nombreAuditor: z.string().min(1, 'Este campo es requerido.'),
  cedulaAuditor: z.string().min(1, 'Este campo es requerido.'),
  profesionAuditor: z.string().min(1, 'Este campo es requerido.'),
  nombreTestigo1: z.string().min(1, 'Este campo es requerido.'),
  cedulaTestigo1: z.string().min(1, 'Este campo es requerido.'),
  profesionTestigo1: z.string().min(1, 'Este campo es requerido.'),
  nombreTestigo2: z.string().min(1, 'Este campo es requerido.'),
  cedulaTestigo2: z.string().min(1, 'Este campo es requerido.'),
  profesionTestigo2: z.string().min(1, 'Este campo es requerido.'),
  nombreServidorSaliente: z.string().min(1, 'Este campo es requerido.'),
  cedulaServidorSaliente: z.string().min(1, 'Este campo es requerido.'),
  designacionServidorSaliente: z.string().min(1, 'Este campo es requerido.'),

  // --- Anexos (SI/NO) ---
  disponeEstadoSituacionPresupuestaria: z.string().optional(),
  disponeRelacionGastosComprometidosNoCausados: z.string().optional(),
  disponeRelacionGastosComprometidosCausadosNoPagados: z.string().optional(),
  disponeEstadoPresupuestarioPorPartidas: z.string().optional(),
  disponeEstadoPresupuestarioDetalleCuentas: z.string().optional(),
  disponeEstadosFinancieros: z.string().optional(),
  disponeBalanceComprobacion: z.string().optional(),
  disponeEstadoSituacionFinanciera: z.string().optional(),
  disponeEstadoRendimientoFinanciero: z.string().optional(),
  disponeEstadoMovimientosPatrimonio: z.string().optional(),
  disponeRelacionCuentasPorCobrar: z.string().optional(),
  disponeRelacionCuentasPorPagar: z.string().optional(),
  disponeRelacionCuentasFondosTerceros: z.string().optional(),
  disponeSituacionFondosAnticipo: z.string().optional(),
  disponeSituacionCajaChica: z.string().optional(),
  disponeActaArqueoCajasChicas: z.string().optional(),
  disponeListadoRegistroAuxiliarProveedores: z.string().optional(),
  disponeReportesLibrosContables: z.string().optional(),
  disponeReportesCuentasBancarias: z.string().optional(),
  disponeReportesConciliacionesBancarias: z.string().optional(),
  disponeReportesRetenciones: z.string().optional(),
  disponeReporteProcesosContrataciones: z.string().optional(),
  disponeReporteFideicomisoPrestaciones: z.string().optional(),
  disponeReporteBonosVacacionales: z.string().optional(),
  disponeCuadroResumenCargos: z.string().optional(),
  disponeCuadroResumenValidadoRRHH: z.string().optional(),
  disponeReporteNominas: z.string().optional(),
  disponeInventarioBienes: z.string().optional(),
  disponeEjecucionPlanOperativo: z.string().optional(),
  incluyeCausasIncumplimientoMetas: z.string().optional(),
  disponePlanOperativoAnual: z.string().optional(),
  disponeClasificacionArchivo: z.string().optional(),
  incluyeUbicacionFisicaArchivo: z.string().optional(),
  disponeRelacionMontosFondosAsignados: z.string().optional(),
  disponeSaldoEfectivoFondos: z.string().optional(),
  disponeRelacionBienesAsignados: z.string().optional(),
  disponeRelacionBienesAsignadosUnidadBienes: z.string().optional(),
  disponeEstadosBancariosConciliados: z.string().optional(),
  disponeListaComprobantesGastos: z.string().optional(),
  disponeChequesEmitidosPendientesCobro: z.string().optional(),
  disponeListadoTransferenciaBancaria: z.string().optional(),
  disponeCaucionFuncionario: z.string().optional(),
  disponeCuadroDemostrativoRecaudado: z.string().optional(),
  disponeRelacionExpedientesAbiertos: z.string().optional(),
  disponeSituacionTesoroNacional: z.string().optional(),
  disponeInfoEjecucionPresupuestoNacional: z.string().optional(),
  disponeMontoDeudaPublicaNacional: z.string().optional(),
  disponeSituacionCuentasNacion: z.string().optional(),
  disponeSituacionTesoroEstadal: z.string().optional(),
  disponeInfoEjecucionPresupuestoEstadal: z.string().optional(),
  disponeSituacionCuentasEstado: z.string().optional(),
  disponeSituacionTesoroDistritalMunicipal: z.string().optional(),
  disponeInfoEjecucionPresupuestoDistritalMunicipal: z.string().optional(),
  disponeSituacionCuentasDistritalesMunicipales: z.string().optional(),
  disponeInventarioTerrenosEjidos: z.string().optional(),
  disponeRelacionIngresosVentaTerrenos: z.string().optional(),

  anexo6: z.string().min(1, 'Este campo es requerido.'),
  anexos: z.string().min(1, 'Este campo es requerido.'),
  accionesAuditoria: z.string().optional(),
  deficienciasActa: z.string().optional(),
});

// --- Esquema para Acta Saliente (PAGA) ---

export const actaSalienteSchema = z.object({
  // --- Datos Generales ---
  email: z
    .string()
    .min(1, 'Campo Requerido')
    .email({ message: 'Debe ser un correo válido.' }),
  rifOrgano: z.string().min(1, 'El RIF es requerido.'),
  denominacionCargoEntrega: z
    .string()
    .min(1, 'La denominación del cargo es requerida.'),
  nombreOrgano: z.string().min(1, 'El nombre del órgano es requerido.'),
  ciudadSuscripcion: z.string().min(1, 'La ciudad es requerida.'),
  estadoSuscripcion: z.string().min(1, 'El estado es requerido.'),
  horaSuscripcion: z.string().min(1, 'La hora es requerida.'),
  fechaSuscripcion: z.string().min(1, 'La fecha es requerida.'),
  direccionOrgano: z.string().min(1, 'La dirección es requerida.'),
  motivoEntrega: z.string().min(1, 'Debe seleccionar un motivo.'),

  // --- Servidores Públicos (Saliente) ---
  nombreServidorSaliente: z.string().min(1, 'Este campo es requerido.'),
  cedulaServidorSaliente: z.string().min(1, 'Este campo es requerido.'),
  designacionServidorSaliente: z.string().min(1, 'Este campo es requerido.'),
  nombreServidorRecibe: z.string().min(1, 'Este campo es requerido.'),
  cedulaServidorRecibe: z.string().min(1, 'Este campo es requerido.'),
  designacionServidorRecibe: z.string().min(1, 'Este campo es requerido.'),

  // --- Anexos (Todos opcionales) ---
  estadoSituacionPresupuestaria: z.string().optional(),
  relacionGastosComprometidosNoCausados: z.string().optional(),
  relacionGastosCausadosNoPagados: z.string().optional(),
  estadoPresupuestarioPorPartidas: z.string().optional(),
  estadoPresupuestarioDetalleCuentas: z.string().optional(),
  estadosFinancieros: z.string().optional(),
  balanceComprobacion: z.string().optional(),
  estadoSituacionFinanciera: z.string().optional(),
  estadoRendimientoFinanciero: z.string().optional(),
  estadoMovimientosPatrimonio: z.string().optional(),
  relacionCuentasPorCobrar: z.string().optional(),
  relacionCuentasPorPagar: z.string().optional(),
  relacionCuentasFondosTerceros: z.string().optional(),
  situacionFondosAnticipo: z.string().optional(),
  situacionCajaChica: z.string().optional(),
  actaArqueoCajasChicas: z.string().optional(),
  listadoRegistroAuxiliarProveedores: z.string().optional(),
  reportesLibrosContables: z.string().optional(),
  reportesCuentasBancarias: z.string().optional(),
  reportesConciliacionesBancarias: z.string().optional(),
  reportesRetenciones: z.string().optional(),
  reporteProcesosContrataciones: z.string().optional(),
  reporteFideicomisoPrestaciones: z.string().optional(),
  reporteBonosVacacionales: z.string().optional(),
  cuadroResumenCargos: z.string().optional(),
  cuadroResumenValidadoRRHH: z.string().optional(),
  reporteNominas: z.string().optional(),
  inventarioBienes: z.string().optional(),
  ejecucionPlanOperativo: z.string().optional(),
  causasIncumplimientoMetas: z.string().optional(),
  planOperativoAnual: z.string().optional(),
  clasificacionArchivo: z.string().optional(),
  ubicacionFisicaArchivo: z.string().optional(),
  anexo6: z.string().optional(), // CORREGIDO: Es opcional hasta el último paso
  anexos: z.string().optional(), // CORREGIDO: Es opcional hasta el último paso
  relacionMontosFondosAsignados: z.string().optional(),
  saldoEfectivoFondos: z.string().optional(),
  relacionBienesAsignados: z.string().optional(),
  relacionBienesAsignadosUnidadBienes: z.string().optional(),
  estadosBancariosConciliados: z.string().optional(),
  listaComprobantesGastos: z.string().optional(),
  chequesEmitidosPendientesCobro: z.string().optional(),
  listadoTransferenciaBancaria: z.string().optional(),
  caucionFuncionario: z.string().optional(),
  cuadroDemostrativoRecaudado: z.string().optional(),
  relacionExpedientesAbiertos: z.string().optional(),
  situacionTesoroNacional: z.string().optional(),
  infoEjecucionPresupuestoNacional: z.string().optional(),
  montoDeudaPublicaNacional: z.string().optional(),
  situacionCuentasNacion: z.string().optional(),
  situacionTesoroEstadal: z.string().optional(),
  infoEjecucionPresupuestoEstadal: z.string().optional(),
  situacionCuentasEstado: z.string().optional(),
  situacionTesoroDistritalMunicipal: z.string().optional(),
  infoEjecucionPresupuestoDistritalMunicipal: z.string().optional(),
  situacionCuentasDistritalesMunicipales: z.string().optional(),
  inventarioTerrenosEjidos: z.string().optional(),
  relacionIngresosVentaTerrenos: z.string().optional(),
  accionesAuditoria: z.string().optional(),
  deficienciasActa: z.string().optional(),
});
//acta saliente schema
export const actaEntranteSchema = z.object({
  // --- Datos Generales ---
  email: z
    .string()
    .min(1, 'Campo Requerido')
    .email({ message: 'Debe ser un correo válido.' }),
  rifOrgano: z.string().min(1, 'El RIF es requerido.'),
  denominacionCargoEntrega: z
    .string()
    .min(1, 'La denominación del cargo es requerida.'),
  nombreOrgano: z.string().min(1, 'El nombre del órgano es requerido.'),
  ciudadSuscripcion: z.string().min(1, 'La ciudad es requerida.'),
  estadoSuscripcion: z.string().min(1, 'El estado es requerido.'),
  horaSuscripcion: z.string().min(1, 'La hora es requerida.'),
  fechaSuscripcion: z.string().min(1, 'La fecha es requerida.'),
  direccionOrgano: z.string().min(1, 'La dirección es requerida.'),
  motivoEntrega: z.string().min(1, 'Debe seleccionar un motivo.'),

  // --- Servidores Públicos y Testigos ---
  nombreServidorEntrante: z.string().min(1, 'Este campo es requerido.'),
  cedulaServidorEntrante: z.string().min(1, 'Este campo es requerido.'),
  profesionServidorEntrante: z.string().min(1, 'Este campo es requerido.'),
  designacionServidorEntrante: z.string().min(1, 'Este campo es requerido.'),
  nombreAuditor: z.string().min(1, 'Este campo es requerido.'),
  cedulaAuditor: z.string().min(1, 'Este campo es requerido.'),
  profesionAuditor: z.string().min(1, 'Este campo es requerido.'),
  nombreTestigo1: z.string().min(1, 'Este campo es requerido.'),
  cedulaTestigo1: z.string().min(1, 'Este campo es requerido.'),
  profesionTestigo1: z.string().min(1, 'Este campo es requerido.'),
  nombreTestigo2: z.string().min(1, 'Este campo es requerido.'),
  cedulaTestigo2: z.string().min(1, 'Este campo es requerido.'),
  profesionTestigo2: z.string().min(1, 'Este campo es requerido.'),
  nombreServidorSaliente: z.string().min(1, 'Este campo es requerido.'),
  cedulaServidorSaliente: z.string().min(1, 'Este campo es requerido.'),
  designacionServidorSaliente: z.string().min(1, 'Este campo es requerido.'),

  // --- Anexos (SI/NO) ---
  disponeEstadoSituacionPresupuestaria: z.string().optional(),
  disponeRelacionGastosComprometidosNoCausados: z.string().optional(),
  disponeRelacionGastosComprometidosCausadosNoPagados: z.string().optional(),
  disponeEstadoPresupuestarioPorPartidas: z.string().optional(),
  disponeEstadoPresupuestarioDetalleCuentas: z.string().optional(),
  disponeEstadosFinancieros: z.string().optional(),
  disponeBalanceComprobacion: z.string().optional(),
  disponeEstadoSituacionFinanciera: z.string().optional(),
  disponeEstadoRendimientoFinanciero: z.string().optional(),
  disponeEstadoMovimientosPatrimonio: z.string().optional(),
  disponeRelacionCuentasPorCobrar: z.string().optional(),
  disponeRelacionCuentasPorPagar: z.string().optional(),
  disponeRelacionCuentasFondosTerceros: z.string().optional(),
  disponeSituacionFondosAnticipo: z.string().optional(),
  disponeSituacionCajaChica: z.string().optional(),
  disponeActaArqueoCajasChicas: z.string().optional(),
  disponeListadoRegistroAuxiliarProveedores: z.string().optional(),
  disponeReportesLibrosContables: z.string().optional(),
  disponeReportesCuentasBancarias: z.string().optional(),
  disponeReportesConciliacionesBancarias: z.string().optional(),
  disponeReportesRetenciones: z.string().optional(),
  disponeReporteProcesosContrataciones: z.string().optional(),
  disponeReporteFideicomisoPrestaciones: z.string().optional(),
  disponeReporteBonosVacacionales: z.string().optional(),
  disponeCuadroResumenCargos: z.string().optional(),
  disponeCuadroResumenValidadoRRHH: z.string().optional(),
  disponeReporteNominas: z.string().optional(),
  disponeInventarioBienes: z.string().optional(),
  disponeEjecucionPlanOperativo: z.string().optional(),
  incluyeCausasIncumplimientoMetas: z.string().optional(),
  disponePlanOperativoAnual: z.string().optional(),
  disponeClasificacionArchivo: z.string().optional(),
  incluyeUbicacionFisicaArchivo: z.string().optional(),
  disponeRelacionMontosFondosAsignados: z.string().optional(),
  disponeSaldoEfectivoFondos: z.string().optional(),
  disponeRelacionBienesAsignados: z.string().optional(),
  disponeRelacionBienesAsignadosUnidadBienes: z.string().optional(),
  disponeEstadosBancariosConciliados: z.string().optional(),
  disponeListaComprobantesGastos: z.string().optional(),
  disponeChequesEmitidosPendientesCobro: z.string().optional(),
  disponeListadoTransferenciaBancaria: z.string().optional(),
  disponeCaucionFuncionario: z.string().optional(),
  disponeCuadroDemostrativoRecaudado: z.string().optional(),
  disponeRelacionExpedientesAbiertos: z.string().optional(),
  disponeSituacionTesoroNacional: z.string().optional(),
  disponeInfoEjecucionPresupuestoNacional: z.string().optional(),
  disponeMontoDeudaPublicaNacional: z.string().optional(),
  disponeSituacionCuentasNacion: z.string().optional(),
  disponeSituacionTesoroEstadal: z.string().optional(),
  disponeInfoEjecucionPresupuestoEstadal: z.string().optional(),
  disponeSituacionCuentasEstado: z.string().optional(),
  disponeSituacionTesoroDistritalMunicipal: z.string().optional(),
  disponeInfoEjecucionPresupuestoDistritalMunicipal: z.string().optional(),
  disponeSituacionCuentasDistritalesMunicipales: z.string().optional(),
  disponeInventarioTerrenosEjidos: z.string().optional(),
  disponeRelacionIngresosVentaTerrenos: z.string().optional(),

  anexo6: z.string().min(1, 'Este campo es requerido.'),
  anexos: z.string().min(1, 'Este campo es requerido.'),
  accionesAuditoria: z.string().optional(),
  deficienciasActa: z.string().optional(),
});
